plugins {
    id 'com.android.application'
}

def versionPropsFile = file("version.properties")
def code = 3
def build = 1

if (versionPropsFile.exists()) {
    def Properties versionProps = new Properties()
    versionProps.load(new FileInputStream(versionPropsFile))
    code = versionProps['VERSION_CODE'].toInteger()
    build = versionProps['VERSION_BUILD'].toInteger()
    
    // Auto-increment build version only during compilation/deployment tasks
    def runTasks = gradle.startParameter.taskNames
    if (runTasks.any { it.contains("assemble") || it.contains("install") || it.contains("bundle") || it.contains("generate") }) {
        build++
        code++
        versionProps['VERSION_CODE'] = code.toString()
        versionProps['VERSION_BUILD'] = build.toString()
        versionProps.store(new FileOutputStream(versionPropsFile), null)
    }
}

android {
    namespace 'com.diaclock.nightstand'
    compileSdk 33

    defaultConfig {
        applicationId "com.diaclock.nightstand"
        minSdk 23
        targetSdk 33
        versionCode code
        versionName "1.1." + build

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def prefix = "DiaNight"
            def version = variant.versionName
            def type = variant.buildType.name
            outputFileName = "${prefix}-v${version}-${type}.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Networking and JSON dependencies
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
    implementation 'com.google.code.gson:gson:2.10.1'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
